# Generated by Django 3.0.5 on 2020-04-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_MA_Backend', '0002_categorizeddomain_websitecategorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('participant_label', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudyCondition',
            fields=[
                ('condition_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('condition_name', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'study_condition',
                'managed': False,
            },
        ),
    ]
