# Generated by Django 3.0.5 on 2020-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_MA_Backend', '0004_privacypointhistoryentry_settingchangeentry_websitevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteVisitCategorization',
            fields=[
                ('website_visit_categorization_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'website_visit_categorization',
                'managed': False,
            },
        ),
    ]
