# Generated by Django 3.0.5 on 2020-05-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_MA_Backend', '0008_popupsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalSession',
            fields=[
                ('modal_session_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modal_type', models.CharField(blank=True, max_length=5, null=True)),
                ('info', models.CharField(blank=True, max_length=400, null=True)),
                ('modal_opened_time', models.DateTimeField(blank=True, null=True)),
                ('modal_closed_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modal_session',
                'managed': False,
            },
        ),
    ]
