# Generated by Django 3.0.5 on 2020-05-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_MA_Backend', '0009_modalsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingChangeEntry',
        ),
    ]
