# Generated by Django 3.0.5 on 2020-05-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_MA_Backend', '0010_delete_settingchangeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationCode',
            fields=[
                ('participation_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('participation_code', models.IntegerField(blank=True, null=True)),
                ('is_taken', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participation_code',
                'managed': False,
            },
        ),
    ]
